# For more information about tox, see https://tox.readthedocs.io/en/latest/
[tox]
envlist = py{312, 313, 314}-{linux,macos,windows}-{pyqt6,pyside6}
isolated_build=true

[gh-actions]
python =
    3.12: py312
    3.13: py313
    3.14: py314

[gh-actions:env]
PLATFORM =
    ubuntu-latest: linux
    macos-latest: macos
    macos-14: macos
    macos-15: macos
    windows-latest: windows

QT_BINDING =
    pyqt6: pyqt6
    pyside6: pyside6

[testenv]
platform =
    macos: darwin
    linux: linux
    windows: win32
passenv =
    CI
    GITHUB_ACTIONS
    DISPLAY
    XAUTHORITY
    NUMPY_EXPERIMENTAL_ARRAY_FUNCTION
    PYVISTA_OFF_SCREEN
    QT_API
extras =
    testing
deps =
    setuptools
    tox
    tox-gh-actions
    pyqt6: PyQt6
    pyside6: PySide6
commands = pytest -v --color=yes --cov=napari_phasors --cov-report=xml
